/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Aula;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    public void TestePessoa(){

        Pessoa pessoa = new Pessoa();
        assertNotNull(pessoa);
    }

    @Test
    public void TesteParametro(){
    Pessoa pessoa = new Pessoa("Banbolim");
    assertNotNull(pessoa);

}

    @Test
    public void TestarConstrutor2Parametros(){
    Pessoa pessoa = new Pessoa("Teste", 1);
    assertNotNull(pessoa);    
    }

    @Test
    public void testarGetNome(){
        Pessoa pessoa = new Pessoa("John Doe");
        assertEquals("John Doe", pessoa.getNome());
    }

    @Test
    public void TestarTrocanome(){
        Pessoa pessoa = new Pessoa("John Doe");
        assertEquals("John Doe", pessoa.getNome());
        pessoa.trocarNome("John2");
        assertEquals("John Doe", pessoa.getNome());
    }

    @Test
    public void TestarTrocanomeMaior18(){
        Pessoa pessoa = new Pessoa("John Doe", 21);
        assertEquals("John Doe", pessoa.getNome());
        pessoa.trocarNome("John2");
        assertEquals("John2", pessoa.getNome());
    }

    @Test
    public void TestarTrocanomeMenor18(){
        Pessoa pessoa = new Pessoa("John Doe", 17);
        assertEquals("John Doe", pessoa.getNome());
        pessoa.trocarNome("John2");
        assertEquals("John Doe", pessoa.getNome());
    }


}